# Run below network policy in Powershell. This blocks incoming DNS requests.  
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: block-dns-ingress
  namespace: kube-system
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  ingress: 
  - from:
    - podSelector: {}
    ports:
    - protocol: UDP
      port: 53
